int createFile(char *file, int absoluteSize);
void readFile(char* filename);
static int searchFile(char *filename);
static void writeFileToDisk(int absoluteBlock, char *file, int size);
static void eraseBlock(int relativeBlock);
static void getFileName(int absoluteBlock, char* filename);
static void writeToFileTable(int absoluteBlock);
static void removeFromFileTable(int absoluteBlock);
static int findFreeBlock();
static void bitmapReserveBlock(int absoluteBlock);
static void bitmapFreeBlock(int absoluteBlock);
static int isBlockReserved(int absoluteBlock);
static void clearFileTable();
static void clearDisk();
void allocateFileSystem();
void formatDisk();
void freeFileSystem();
void printDirectory();
static void getFileContents(int absoluteBlock, char* filecontents);
void deleteFile(char *filename);
void writeToFile(char* filename, char *sourceFile);